import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Kumbh_Sans, Inter } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import { Providers } from "./providers";
import Link from "next/link";
import "./globals.css";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Chris Ford - Indie Developer",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${kumbhSans.variable} ${inter.variable} antialiased`}
      >
        <ThemeInit />
        {/* HEADER (sticky) */}
        <header className="sticky top-0 z-40 w-full border-b border-gray-200 bg-white/90 backdrop-blur dark:border-gray-700 dark:bg-gray-900/80">
          <div className="mx-auto flex max-w-screen-xl items-center justify-between px-4 py-3">
            <Link href="/" className="font-kumbh-sans text-xl font-bold text-gray-900 dark:text-white">
              Chris Ford
            </Link>

            <nav className="hidden items-center gap-6 md:flex">
              <a href="#about" className="nav-link">About</a>
              {/*<a href="#projects" className="nav-link">Projects</a>*/}
              <a href="#contact" className="nav-link">Contact</a>
            </nav>

            <div className="flex items-center gap-4">
              {/* Social icons */}
              <a
                href="https://youtube.com/YOURCHANNEL"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23.5 6.2a2.9 2.9 0 0 0-2-2c-1.8-.5-9.5-.5-9.5-.5s-7.7 0-9.5.5a2.9 2.9 0 0 0-2 2C0 8.1 0 12 0 12s0 3.9.5 5.8a2.9 2.9 0 0 0 2 2c1.8.5 9.5.5 9.5.5s7.7 0 9.5-.5a2.9 2.9 0 0 0 2-2c.5-1.9.5-5.8.5-5.8s0-3.9-.5-5.8zM9.6 15.6v-7.2L15.8 12l-6.2 3.6z" />
                </svg>
              </a>
              <a
                href="https://twitter.com/YOURHANDLE"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
              >
                <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23 2.999a9.56 9.56 0 0 1-2.828.807A4.936 4.936 0 0 0 22.337.365a9.864 9.864 0 0 1-3.127 1.184 4.92 4.92 0 0 0-8.388 4.482 13.95 13.95 0 0 1-10.15-5.144 4.822 4.822 0 0 0-.664 2.475 4.92 4.92 0 0 0 2.188 4.1 4.9 4.9 0 0 1-2.229-.616v.06a4.93 4.93 0 0 0 3.946 4.827 4.902 4.902 0 0 1-2.224.084 4.93 4.93 0 0 0 4.604 3.417 9.873 9.873 0 0 1-6.102 2.104c-.396 0-.788-.023-1.175-.068A13.945 13.945 0 0 0 7.548 21c9.057 0 14.01-7.496 14.01-13.986 0-.21-.005-.423-.014-.633A10.025 10.025 0 0 0 23 2.999z" />
                </svg>
              </a>
            </div>
          </div>
        </header>
        <Providers>
          {children}
        </Providers>
        {/* FOOTER */}
        <footer className="mt-24 w-full border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900">
          <div className="max-w-screen-xl mx-auto px-4 py-8 flex flex-col md:flex-row items-center justify-between gap-4">
            {/* Left side */}
            <p className="text-sm text-gray-500 dark:text-gray-400">
              © {new Date().getFullYear()} Chris Ford — All rights reserved.
            </p>

            {/* Right side */}
            <div className="flex items-center gap-4">
              <a
                href="https://www.youtube.com/channel/UCOneYkl50C8p9PgK5aWIV0A"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-500 hover:text-gray-900 dark:hover:text-white transition"
              >
                <svg
                  className="h-5 w-5"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M23.5 6.2a2.9 2.9 0 0 0-2-2c-1.8-.5-9.5-.5-9.5-.5s-7.7 0-9.5.5a2.9 2.9 0 0 0-2 2C0 8.1 0 12 0 12s0 3.9.5 5.8a2.9 2.9 0 0 0 2 2c1.8.5 9.5.5 9.5.5s7.7 0 9.5-.5a2.9 2.9 0 0 0 2-2c.5-1.9.5-5.8.5-5.8s0-3.9-.5-5.8zM9.6 15.6v-7.2L15.8 12l-6.2 3.6z" />
                </svg>
              </a>
              <a
                href="https://x.com/fordchristoph3r"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-500 hover:text-gray-900 dark:hover:text-white transition"
              >
                <svg
                  className="h-5 w-5"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M23 2.999a9.56 9.56 0 0 1-2.828.807A4.936 4.936 0 0 0 22.337.365a9.864 9.864 0 0 1-3.127 1.184 4.92 4.92 0 0 0-8.388 4.482 13.95 13.95 0 0 1-10.15-5.144 4.822 4.822 0 0 0-.664 2.475 4.92 4.92 0 0 0 2.188 4.1 4.9 4.9 0 0 1-2.229-.616v.06a4.93 4.93 0 0 0 3.946 4.827 4.902 4.902 0 0 1-2.224.084 4.93 4.93 0 0 0 4.604 3.417 9.873 9.873 0 0 1-6.102 2.104c-.396 0-.788-.023-1.175-.068A13.945 13.945 0 0 0 7.548 21c9.057 0 14.01-7.496 14.01-13.986 0-.21-.005-.423-.014-.633A10.025 10.025 0 0 0 23 2.999z" />
                </svg>
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
